version: '3.7'
services:
  feeder_redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass redis --appendonly yes
    volumes:
      - .docker/redis:/var/lib/postgresql/data
    ports:
      - 6377:6379
    restart: always

  feeder_mysql:
    image: mysql:8.0
    container_name: feeder_mysql
    restart: unless-stopped
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feeder
    volumes:
      - ./docker/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 300s
      interval: 10s
      retries: 10
    networks:
      - server

  feeder_php:
    container_name: feeder_php
    build:
      context: .docker/php/php8.0
    restart: always
    ports:
      - "9080:9000"
    volumes:
      - "./backend:/var/www/html"
    depends_on:
      feeder_mysql:
        condition: service_healthy
    networks:
      - server

  feeder_nginx:
    container_name: feeder_nginx
    build:
      context: .docker/nginx
    volumes:
      - "./backend:/var/www/html"
    ports:
      - "8085:80"
    restart: always
    working_dir: /var/www/html
    networks:
      - server

  feeder_frontend:
    container_name: feeder_frontend
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    image: frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - 8003:8080
    networks:
      - server

networks:
  server:
    driver: bridge